/**
 * LCM / configurator product phrase pack — BOM fields, foam/wool catalog language.
 * Loaded together with document + game-world packs; same deterministic scan rules apply.
 */
export const SUSO_PHRASE_PACK_CONFIGURATOR = [
  { phrase: "foam pad", category: "product_type", canonical: "foam", pack: "lcm" },
  { phrase: "tufted wool", category: "product_type", canonical: "wool", pack: "lcm" },
  { phrase: "wool pad", category: "product_type", canonical: "wool", pack: "lcm" },
  { phrase: "white loop", category: "loop_type", canonical: "White Loop", pack: "lcm" },
  { phrase: "black loop", category: "loop_type", canonical: "Black Loop", pack: "lcm" },
  { phrase: "no loop", category: "loop_type", canonical: "No Loop", pack: "lcm" },
  { phrase: "with hole", category: "finished_pad", canonical: "With Hole", pack: "lcm" },
  { phrase: "no hole", category: "finished_pad", canonical: "No Hole", pack: "lcm" },
  { phrase: "finished pad", category: "field", canonical: "foamHole", pack: "lcm" },
  { phrase: "loop type", category: "field", canonical: "foamLoopType", pack: "lcm" },
  { phrase: "pad size", category: "field", canonical: "foamPadSize", pack: "lcm" },
  { phrase: "final od", category: "field", canonical: "woolPadSize", pack: "lcm" },
  { phrase: "nap length", category: "field", canonical: "woolNap", pack: "lcm" },
  { phrase: "backing type", category: "field", canonical: "woolBacking", pack: "lcm" },
  { phrase: "poly type", category: "field", canonical: "woolPoly", pack: "lcm" },
  { phrase: "sturdyness", category: "field", canonical: "woolMil", pack: "lcm" },
  { phrase: "mil", category: "field", canonical: "woolMil", pack: "lcm" },
  { phrase: "my custom print", category: "print_type", canonical: "Customer Sample Print", pack: "lcm" },
  { phrase: "customer sample print", category: "print_type", canonical: "Customer Sample Print", pack: "lcm" },
  { phrase: "custom print", category: "print_type", canonical: "Customer Sample Print", pack: "lcm" },
  { phrase: "custom artwork", category: "print_type", canonical: "Customer Sample Print", pack: "lcm" },
  { phrase: "my logo", category: "print_type", canonical: "Customer Sample Print", pack: "lcm" },
  { phrase: "our logo", category: "print_type", canonical: "Customer Sample Print", pack: "lcm" },
  { phrase: "customer logo", category: "print_type", canonical: "Customer Sample Print", pack: "lcm" },
  { phrase: "their logo", category: "print_type", canonical: "Customer Sample Print", pack: "lcm" },
  { phrase: "lc print", category: "print_type", canonical: "LC Print", pack: "lcm" },
  { phrase: "no print", category: "print_type", canonical: "No Print", pack: "lcm" },
  { phrase: "curved", category: "orientation", canonical: "Curved", pack: "lcm" },
  { phrase: "flat", category: "orientation", canonical: "Flat", pack: "lcm" },
  { phrase: "requested by", category: "field", canonical: "reqName", pack: "lcm" },
  { phrase: "sample name", category: "field", canonical: "sampleName", pack: "lcm" },
  { phrase: "bill of materials", category: "intent", canonical: "export_bom", pack: "lcm" },
  { phrase: "bom export", category: "intent", canonical: "export_bom", pack: "lcm" },
  { phrase: "grind dia", category: "concept", canonical: "grinded_loop_dia", pack: "lcm" },
  { phrase: "grinded loop", category: "concept", canonical: "grinded_loop_dia", pack: "lcm" },
  { phrase: "wheel size", category: "concept", canonical: "wheel", pack: "lcm" },
  { phrase: "foam color", category: "field", canonical: "foamColor", pack: "lcm" },
  { phrase: "foam thickness", category: "field", canonical: "foamThickness", pack: "lcm" },
];
